# Generated by Django 3.0.4 on 2020-07-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200702_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=120)),
                ('phone', models.BigIntegerField()),
                ('pancard', models.CharField(max_length=20)),
                ('amount', models.BigIntegerField()),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
